minsalsifda_homepage:
    path:     /hello/{name}
    defaults: { _controller: MinsalsifdaBundle:Default:index }

Minsalsifda_ctltipodependencia:
    resource: "@MinsalsifdaBundle/Controller/"
    prefix: /
    type: annotation